function plotGCMgrid(Grid)
% function plotGCMgrid(Grid)
% plots the grid generated by getGCMgrid function 


% get grid corner values for inside the country bounding box
x = Grid.Country.long;
y = Grid.Country.lat;

% plot the grid 
plot(ones(13,1)*x, (y')*ones(1,60),'k')
plot((ones(13,1)*x)', ((y')*ones(1,60))','k')
title(country)
