function plotGCMgrid(Grid,c)
% function plotGCMgrid(Grid)
% plots the grid generated by getGCMgrid function 


% get grid corner values for inside the country bounding box
x = Grid.Country.long;
y = Grid.Country.lat;

% plot the grid 
plot(ones(13,1)*x, (y')*ones(1,60),c); hold on
plot((ones(13,1)*x)', ((y')*ones(1,60))',c)

